name = "LinearRegression"
uuid = "92481ed7-9fb7-40fd-80f2-46fd0f076581"
authors = ["ST John <st--@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
